version: "3"
app:
    build: .
    ports:
        - '4200:4200'
        - '49153:49153'
    volumes:
        - .:/app/
        - /app/node_modules/
    environment:
        - NODE_ENV=dev
    command: ash -c "yarn install && yarn start"